### ISSUE TITLE
Escape new lines in messages

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/timber-node#31]
In our other libraries we escape new lines so that multi-line messages show up as a single event. This should be done low-level so that all messages get this feature (regardless of the source).

Ex:

```
My\nmessage
```

Would become:

```
My\\nmessage
```

**Comment by ariamckinley** [comment]
So I don't think it's necessary for the node lib, since it's currently patching the console functions (which means it captures the entire log message at once). If I add a newline escaping function to the log class multiline logs appear in timber like this in thor:

```
Invalid domain error!\n at search (/home/garet/code/flybot/api/lib/actions/search.js:11:11)\n at Layer.handle [as handle_request] (/home/garet/code/flybot/api/node_modules/express/lib/router/layer.js:95:5)\n at next (/home/garet/code/flybot/api/node_modules/express/lib/router/route.js:131:13)\n at Route.dispatch (/home/garet/code/flybot/api/node_modules/express/lib/router/route.js:112:3)\n at Layer.handle [as handle_request] (/home/garet/code/flybot/api/node_modules/express/lib/router/layer.js:95:5)\n at /home/garet/code/flybot/api/node_modules/express/lib/router/index.js:277:22\n at param (/home/garet/code/flybot/api/node_modules/express/lib/router/index.js:349:14)\n at param (/home/garet/code/flybot/api/node_modules/express/lib/router/index.js:365:14)\n at Function.process_params (/home/garet/code/flybot/api/node_modules/express/lib/router/index.js:410:3)\n at next (/home/garet/code/flybot/api/node_modules/express/lib/router/index.js:271:10)
```

Without the escaping function multiline logs look normal. One thing I did notice was that multiline messages aren't being rendered correctly on thor

![image](https://user-images.githubusercontent.com/1624279/29145012-2987e4da-7d29-11e7-9d0d-a58d9def044c.png)

But inside the inspector it looks like the logs are being formatted correctly

![image](https://user-images.githubusercontent.com/1624279/29145101-8fdd8ac8-7d29-11e7-9703-0fb64ebd764e.png)


Thor should be rendering multiline logs exactly how the appear in stdout, correct? If so I'll go ahead and open an issue on thor for this. Should be a simple fix.

**Comment by binarylogic** [comment]
Nice. Correct, the console should be rendering new lines appropriately. We have an issue open for that. I'll see if we can prioritize it.
