### ISSUE TITLE
Update express middleware to work with Winston

### ISSUE THREAD

**Issue by ariamckinley** [vectordotdev/timber-node#38]
I discovered today that the express middleware does not work with winston. This is because winston uses it's own logger instead of `console.log`.

My first thought was to convert the express middleware to a function that accepts an optional logger and returns the middleware. But the solution isn't that trivial, since the function signature of `console.log` vs `winston.log` is completely different.

Going to have to put some more thought into this.

**Comment by ariamckinley** [comment]
Obviously the end user can solve this themselves by user `timber.install` along with `winston.add`, but it's not an ideal solution. Not to mention, if they don't remove the default `stdout` transport using `winston.remove`, all logs will get double-sent to us (once from the winston transport and once from draining `stdout`)

**Comment by binarylogic** [comment]
What do winston users currently use / do for express middleware (outside of Timber)?

**Comment by ariamckinley** [comment]
[express-winston](https://github.com/bithavoc/express-winston) seems to be the most popular. Should we just leave it up to them to use a third party middleware instead of making ours adaptable?

**Comment by binarylogic** [comment]
No because the log message and structure will need to conform to our schema. We can use these libraries as prototypes though. There appears to be a lot of configuration that we won't need. I have a feeling we could do something similar with much less code.

Also, before you get knee deep in this matrix of loggers and integrations let's decide on the best approach. I'm thinking it might be beneficial to define an abstract logginf interface for our own internal use. This way our express middleware can use this interface instead of having to worry about the logger being implemented. Does that make sense? This interface would need to be told which logger is being used, but after that we can funnel all internal calls through it.

**Comment by binarylogic** [comment]
Should we close in favor of https://github.com/timberio/timber-node/issues/42 ?
