### ISSUE TITLE
Create a destination integration with Bunyan

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/timber-node#43]
I want to do exactly what we did with winston but for the [bunyan logger](https://github.com/trentm/node-bunyan). If Bunyan allows us to specify an arbitrary stream this might be as simple as adding an example in the README. If not, we need to create a proper backend to support this.

**Comment by ariamckinley** [comment]
So bunyan *does* support arbitrary streams as the backend for the logger, but it logs as JSON. So even though it's sending the log line to timber as JSON, it's not parsed because it's not in a recognized format.

I see two possible solutions for this:
1. create an bunyan-specific abstraction ontop of our https transport that automatically handles restructuring the JSON to match our schema
2. create a [bunyan serializer](https://github.com/trentm/node-bunyan#serializers) that would do the same thing, but allow the stream to be set to our existing https transport

The benefit of [1] would be that it is slightly easier to implement for the end user and has less room for error. And the benefit of [2] would be that it would give us less overhead since we wouldn't have to maintain an additional transport, but if improperly setup by the end user, will cause their log lines to not get parsed by timber.

The api of [1] would look something like this:
```js
const log = bunyan.createLogger({
  name: "timber",
  stream: new timber.transports.bunyan(api-key)
})
```

and the implementation of [2] would be something like

```js
const log = bunyan.createLogger({
  name: "timber",
  stream: new timber.transports.HTTPS(api-key),
  serializer: timber.serializers.bunyan
})
```

Let me know your thoughts on which would be a better solution, or if you have a different solution entirely so we can get this rolling. Either way, it's an easy implementation.

**Comment by binarylogic** [comment]
Just noting that we discussed a stream adapter that would transform bunyan logs into our JSON schema structure.
